@REM ----------------------------------------------------------------------------
@REM Licensed to the Apache Software Foundation (ASF)
@REM under one or more contributor license agreements.  See the NOTICE file
@REM distributed with this work for additional information
@REM regarding copyright ownership.  The ASF licenses this file
@REM to you under the Apache License, Version 2.0 (the
@REM "License"); you may not use this file except in compliance
@REM with the License.  You may obtain a copy of the License at
@REM
@REM    http://www.apache.org/licenses/LICENSE-2.0
@REM
@REM Unless required by applicable law or agreed to in writing,
@REM software distributed under the License is distributed on an
@REM "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
@REM KIND, either express or implied.  See the License for the
@REM specific language governing permissions and limitations
@REM under the License.
@REM
@REM MAVEN_HOME - location of maven's installed home dir
@REM HAVE_TILDE - true if MAVEN_HOME or MAVEN_BASE_DIR contains at least one tilde
@REM M2_HOME - location of maven's installed home dir
@REM MAVEN_BATCH_PAUSE - set to 'on' to wait for a keystroke before ending
@REM MAVEN_BATCH_ECHO - set to 'on' to echo current directory and maven version
@REM This batch script is called from scripts/mvn.cmd scripts generated by Maven wrapper distribution
@REM in order to promote/convert all .bat scripts to use the .cmd script instead.
@REM once the global signature is changed to .cmd, all bat scripts will be removed.
@echo off

set ERROR_CODE=0

@REM To isolate internal variables from possible post scripts, we use another setlocal
setlocal

set MAVEN_CMD_LINE_ARGS=%*

@REM check for post script, e.g. after.bat on Windows with negative exit code
@REM if not exist "%POST_BUILD_CMD%" goto skipPostCmd

@REM A newer version of Maven may be better than the older one; however, we still want
@REM to cache the Maven wrapper in case there are connectivity issues
@REM Fallback to curl if wget is not available
if not defined MVNW_REPOURL (
  set MVNW_REPOURL=https://repo.maven.apache.org/maven2
)

if not defined MVNW_USERNAME (
  set MVNW_USERNAME=
)

if not defined MVNW_PASSWORD (
  set MVNW_PASSWORD=
)

@REM First, find java

if not defined JAVA_HOME goto err

@REM Remove trailing spaces from JAVA_HOME
setlocal enabledelayedexpansion
for /l %%A in (1,1,32) do if "!JAVA_HOME:~-1!"==" " set "JAVA_HOME=!JAVA_HOME:~0,-1!"
endlocal & set "JAVA_HOME=%JAVA_HOME%"

@REM Verify the Java command is available
if not exist "%JAVA_HOME%\bin\java.exe" (
  echo Error: JAVA_HOME is not properly set: "%JAVA_HOME%"
  echo.
  echo Please set the JAVA_HOME variable in your environment to match the
  echo location of your Java installation.
  goto error
)

if "%JAVA_HOME%" == "" (
  echo Error: JAVA_HOME not found in your environment. Please set the JAVA_HOME variable in your environment to match the location of your Java installation.
  goto error
)

@REM Find Maven wrapper jar
set MAVEN_WRAPPER_JAR="%MAVEN_HOME%\wrapper\maven-wrapper.jar"
if exist "%MAVEN_WRAPPER_JAR%" (
  set "WRAPPER_JAR=%MAVEN_WRAPPER_JAR%"
) else (
  echo Downloading Maven wrapper...
  if defined MVNW_USERNAME (
    if defined MVNW_PASSWORD (
      for /f "usebackq tokens=*" %%A in (`powershell -Command "if (-not (Test-Path '%MAVEN_HOME%\wrapper')) { New-Item -ItemType Directory -Path '%MAVEN_HOME%\wrapper' -Force | Out-Null }; (New-Object System.Net.WebClient).DownloadFile('https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar', '%MAVEN_HOME%\wrapper\maven-wrapper.jar')"`) do @set WRAPPER_JAR=%%A
    ) else (
      for /f "usebackq tokens=*" %%A in (`powershell -Command "if (-not (Test-Path '%MAVEN_HOME%\wrapper')) { New-Item -ItemType Directory -Path '%MAVEN_HOME%\wrapper' -Force | Out-Null }; (New-Object System.Net.WebClient).DownloadFile('https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper.jar', '%MAVEN_HOME%\wrapper\maven-wrapper.jar')"`) do @set WRAPPER_JAR=%%A
    )
  ) else (
    for /f "usebackq tokens=*" %%A in (`powershell -Command "if (-not (Test-Path '%MAVEN_HOME%\wrapper')) { New-Item -ItemType Directory -Path '%MAVEN_HOME%\wrapper' -Force | Out-Null }; (New-Object System.Net.WebClient).DownloadFile('https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper.jar', '%MAVEN_HOME%\wrapper\maven-wrapper.jar')"`) do @set WRAPPER_JAR=%%A
  )
)

@REM Método simplificado: chamar Maven diretamente se disponível
if exist "%JAVA_HOME%\bin\java.exe" (
  echo Detectado Java em: %JAVA_HOME%
  echo Tentando usar Maven localmente...
  
  if exist "C:\Users\Antonino\AppData\Local\apache-maven\apache-maven-3.9.14\bin\mvn.cmd" (
    call "C:\Users\Antonino\AppData\Local\apache-maven\apache-maven-3.9.14\bin\mvn.cmd" %MAVEN_CMD_LINE_ARGS%
    goto end
  )
  
  @REM Se Maven wrapper JAR existir, usar para download
  if exist "%CD%\.mvn\wrapper\maven-wrapper.jar" (
    echo Executando Maven via wrapper...
    "%JAVA_HOME%\bin\java.exe" ^
      -classpath ""%CD%\.mvn\wrapper\maven-wrapper.jar"" ^
      "-Dmaven.multiModuleProjectDirectory=%CD%" ^
      org.apache.maven.wrapper.MavenWrapperMain %MAVEN_CMD_LINE_ARGS%
    
    if %ERRORLEVEL% neq 0 (
      echo Maven wrapper exited with error code %ERRORLEVEL%
      goto error
    )
    goto end
  ) else (
    echo Erro: Maven wrapper JAR nao encontrado em %CD%\.mvn\wrapper\maven-wrapper.jar
    echo Por favor, copie o arquivo maven-wrapper.jar para esse diretorio
    goto error
  )
) else (
  echo Erro: JAVA_HOME nao esta configurado corretamente: "%JAVA_HOME%"
  goto err
)

:err
echo Error: JAVA_HOME environment variable is not defined correctly
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

:error
exit /b 1

:end
exit /b %ERROR_CODE%
